export const INCREMENT = 'INCREMENT'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const RETRIEVE_ARTICLES_BY_FILTER = 'RETRIEVE_ARTICLES_BY_FILTER'

export const APPLY_ARTICLE_FILTER_BY_DATE = 'APPLY_ARTICLE_FILTER_BY_DATE'

export const APPLY_ARTICLE_FILTER_BY_INDEX = 'APPLY_ARTICLE_FILTER_BY_INDEX'

export const APPLY_ARTICLE_FILTER_BY_USER = 'APPLY_ARTICLE_FILTER_BY_USER'